meta_product_name: "Marginalia"
meta_title: "Marginalia - La plateforme où les livres vivent après la dernière page"
meta_description: "Une app sociale et esthétique qui permet de consigner ses lectures, poster des reviews, suivre ses stats et découvrir via ses amis."
meta_image: "/images/ogimage.png" # should exist in `app/assets/images/`
